# Generated by Django 5.0.14 on 2026-07-02 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IdempotencyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, verbose_name='멱등성 키')),
                ('scope', models.CharField(max_length=100, verbose_name='요청 범위')),
                ('response_status', models.PositiveSmallIntegerField(verbose_name='응답 상태 코드')),
                ('response_body', models.TextField(verbose_name='응답 본문(JSON)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
            ],
            options={
                'indexes': [models.Index(fields=['created_at'], name='api_idempot_created_d9784e_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='idempotencyrecord',
            constraint=models.UniqueConstraint(fields=('key', 'scope'), name='uniq_idempotency_key_scope'),
        ),
    ]
