# Generated by Django 5.0.14 on 2026-07-01 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='관련 작업 ID')),
                ('action_type', models.CharField(choices=[('create', '생성'), ('update', '수정'), ('delete', '삭제'), ('complete', '완료'), ('review', '검토')], max_length=20, verbose_name='활동 종류')),
                ('actor_name', models.CharField(default='NULL', max_length=100, verbose_name='수행자')),
                ('message', models.TextField(verbose_name='활동 세부 메세지')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='발생 일시')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
