# Generated by Django 5.0.14 on 2026-07-01 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='작업 ID')),
                ('title', models.CharField(max_length=255, verbose_name='작업 제목')),
                ('description', models.TextField(blank=True, default='', verbose_name='작업 설명')),
                ('creator', models.CharField(default='Unknown', max_length=100, verbose_name='작업 생성자')),
                ('status', models.CharField(choices=[('todo', 'To-Do'), ('inprogress', 'In Progress'), ('review', 'Review'), ('done', 'Done')], default='todo', max_length=20, verbose_name='진행 상태')),
                ('priority', models.CharField(default='medium', max_length=20, verbose_name='우선순위')),
                ('category', models.CharField(blank=True, default='', max_length=100, verbose_name='카테고리')),
                ('due_date', models.CharField(blank=True, default='', max_length=50, verbose_name='마감일')),
                ('assignee_id', models.CharField(blank=True, default='', max_length=100, verbose_name='담당자 ID')),
                ('roles', models.TextField(blank=True, default='[]', verbose_name='관련 역할군들 (JSON)')),
                ('has_unreflected_review', models.BooleanField(default=False, verbose_name='미반영 검토 의견 존재 여부')),
                ('last_review_added_at', models.CharField(blank=True, default='', max_length=100, verbose_name='마지막 검토 일시')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일시')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubTask',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='하위 작업 ID')),
                ('title', models.CharField(max_length=255, verbose_name='하위 작업 제목')),
                ('completed', models.BooleanField(default=False, verbose_name='완료 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='tasks.task', verbose_name='상위 작업')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
